"use strict";

GSUsetTemplate( "gs-main", () =>
	GSUcreateDiv( { id: "root", class: "noauth" },
		GSUcreateFlex( { id: "bg", x: true, inert: false },
			GSUcreateDiv( { "data-side": "start" },
				GSUcreateDiv( { class: "bg-island", "data-name": "drums" } ),
				GSUcreateDiv( { class: "bg-island", "data-name": "ipod" } ),
				GSUcreateDiv( { class: "bg-island", "data-name": "piano" } ),
			),
			GSUcreateDiv( { "data-side": "end" },
				GSUcreateDiv( { class: "bg-island", "data-name": "tape" } ),
				GSUcreateDiv( { class: "bg-island", "data-name": "ampli" } ),
				GSUcreateDiv( { id: "bg-volcan" } ),
			),
		),
		GSUcreateDiv( { id: "main" },
			GSUcreateDiv( { id: "head" },
				GSUcreateA( { id: "headIcon", class: "headLink", href: "#/" } ),
				GSUcreateAExt( { id: "headNewCmp", class: "headLink", href: DAWURL, title: "Create a new composition" },
					GSUcreateIcon( { icon: "music" } ),
					GSUcreateIcon( { icon: "plus" } ),
					GSUcreateIcon( { icon: "plus" } ),
				),
				GSUcreateA( { id: "headUser", class: "headLink" },
					GSUcreateDiv( { id: "headUsername" } ),
					GSUcreateElement( "gsui-com-avatar", { id: "headAvatar" } ),
				),
				GSUcreateA( { id: "headAuth", class: "headLink gsuiIcon", href: "#/auth", "data-icon": "login", "data-spin": "on", title: "Authentication" } ),
			),
			GSUcreateDiv( { id: "pages" },
				GSUcreateDiv( { id: "loader" },
					GSUcreateIcon( { spin: true } ),
				),
				GSUcreateDiv( { id: "error" },
					GSUcreateSpan( { id: "errorLabel" }, "error" ),
					GSUcreateSpan( { id: "errorCode" } ),
				),
			),
			GSUcreateDiv( { id: "footer" },
				GSUcreateDiv( { id: "footerSocialLinks" },
					GSUcreateAExt( { class: "gsuiIcon", "data-icon": "br-github", href: "//github.com/gridsound" } ),
					GSUcreateAExt( { class: "gsuiIcon", "data-icon": "br-codepen", href: "//codepen.io/gridsound" } ),
					GSUcreateAExt( { class: "gsuiIcon", "data-icon": "br-discord", href: "//discord.gg/NUYxHAg" } ),
					GSUcreateAExt( { class: "gsuiIcon", "data-icon": "br-bluesky", href: "//bsky.app/profile/gridsound.com" } ),
					GSUcreateAExt( { class: "gsuiIcon", "data-icon": "br-youtube", href: "//youtube.com/@gridsound" } ),
					GSUcreateAExt( { class: "gsuiIcon", "data-icon": "br-facebook", href: "//facebook.com/gridsound" } ),
				),
				GSUcreateDiv( { id: "footerCopyright" }, `© ${ ( new Date() ).getFullYear() } gridsound.com all rights reserved` ),
			),
		),
	),
);
