"use strict";

GSUsetTemplate( "gs-main", () =>
	GSUcreateDiv( { id: "main", class: "noauth" },
		GSUcreateDiv( { id: "main-bg", inert: true },
			GSUcreateDiv( { class: "main-bg-island", "data-name": "ipod" } ),
			GSUcreateDiv( { class: "main-bg-island", "data-name": "piano" } ),
			GSUcreateDiv( { class: "main-bg-island", "data-name": "drums" } ),
			GSUcreateDiv( { class: "main-bg-island", "data-name": "tape" } ),
			GSUcreateDiv( { class: "main-bg-island", "data-name": "ampli" } ),
		),
		GSUcreateDiv( { id: "head" },
			GSUcreateA( { id: "headIcon", class: "headLink", href: "#/" } ),
			GSUcreateAExt( { id: "headNewCmp", class: "headLink", href: DAWURL, title: "Create a new composition" },
				GSUcreateIcon( { icon: "music" } ),
				GSUcreateIcon( { icon: "plus" } ),
				GSUcreateIcon( { icon: "plus" } ),
			),
			GSUcreateA( { id: "headUser", class: "headLink" },
				GSUcreateDiv( { id: "headUsername" } ),
				GSUcreateElement( "gsui-com-avatar", { id: "headAvatar" } ),
			),
			GSUcreateA( { id: "headAuth", class: "headLink gsuiIcon", href: "#/auth", "data-icon": "login", "data-spin": "on", title: "Authentication" } ),
		),
		GSUcreateDiv( { id: "pages" },
			GSUcreateDiv( { id: "loader" },
				GSUcreateIcon( { spin: true } ),
			),
			GSUcreateDiv( { id: "error" },
				GSUcreateSpan( { id: "errorLabel" }, "error" ),
				GSUcreateSpan( { id: "errorCode" } ),
			),
		),
		GSUcreateDiv( { id: "footer" },
			GSUcreateDiv( { id: "footerSocialsLink" },
				GSUcreateAExt( { class: "gsuiIcon", "data-icon": "br-github", href: "//github.com/gridsound" } ),
				GSUcreateAExt( { class: "gsuiIcon", "data-icon": "br-codepen", href: "//codepen.io/gridsound" } ),
				GSUcreateAExt( { class: "gsuiIcon", "data-icon": "br-discord", href: "//discord.gg/NUYxHAg" } ),
				GSUcreateAExt( { class: "gsuiIcon", "data-icon": "br-twitter", href: "//twitter.com/gridsound" } ),
				GSUcreateAExt( { class: "gsuiIcon", "data-icon": "br-youtube", href: "//youtube.com/@gridsound" } ),
				GSUcreateAExt( { class: "gsuiIcon", "data-icon": "br-facebook", href: "//facebook.com/gridsound" } ),
			),
			GSUcreateDiv( { id: "footerCopyright" }, `© ${ ( new Date() ).getFullYear() } gridsound.com all rights reserved` ),
		),
	),
);
