"use strict";

GSUsetTemplate( "gscoAuth", () =>
	$.$div( { class: "page", id: "authPage" },
		$.$elem( "form", { class: "form", id: "authPageSignup" },
			$.$div( { class: "form-title" }, "Create a personal account" ),
			$.$label( { class: "field" },
				$.$span( { class: "field-label" }, "Email" ),
				$.$input( { class: "field-input", id: "authPageSignupEmail", type: "email", name: "email", required: true, maxlength: 128, placeholder: "eg: janedoe@example.com" } ),
			),
			$.$label( { class: "field" },
				$.$span( { class: "field-label" }, "Username" ),
				$.$input( { class: "field-input", id: "authPageSignupUsername", type: "text", name: "username", required: true, minlength: 4, maxlength: 32, pattern: "[a-zA-Z0-9_]*" } ),
			),
			$.$label( { class: "field" },
				$.$span( { class: "field-label" }, "Password" ),
				$.$input( { class: "field-input", id: "authPageSignupPass", type: "password", name: "pass", required: true, minlength: 6 } ),
			),
			$.$div( { class: "form-error", id: "authPageSignupError" } ),
			$.$div( { class: "form-btns" },
				$.$elem( "gsui-com-button", { id: "authPageSignupBtn", type: "submit", text: "Sign up" } ),
			),
		),
		$.$elem( "form", { class: "form", id: "authPageLogin" },
			$.$div( { class: "form-title" }, "Log in to GridSound" ),
			$.$label( { class: "field" },
				$.$span( { class: "field-label" }, "Email (or username)" ),
				$.$input( { class: "field-input", id: "authPageLoginEmail", type: "text", name: "email", required: true } ),
			),
			$.$label( { class: "field" },
				$.$span( { class: "field-label" }, "Password" ),
				$.$input( { class: "field-input", id: "authPageLoginPass", type: "password", name: "pass", required: true } ),
			),
			$.$div( { id: "authPageLoginForgot" },
				$.$link( { href: "#/forgotPassword" }, "Forgot password ?" ),
			),
			$.$div( { class: "form-error", id: "authPageLoginError" } ),
			$.$div( { class: "form-btns" },
				$.$elem( "gsui-com-button", { id: "authPageLoginBtn", type: "submit", text: "Log in" } ),
			),
		),
	),
);
