"use strict";

$.$setTemplate( "gscoResetPass", () =>
	$.$div( { class: "page", id: "resetpassPage" },
		$.$elem( "form", { class: "form", id: "resetpassForm" },
			$.$div( { class: "form-title" }, "Reset password" ),
			$.$div( { class: "form-intro" },
				$.$div( null, "Set a new password." ),
				$.$div( null, "Your password has been changed successfully." ),
			),
			$.$label( { class: "field" },
				$.$span( { class: "field-label" }, "New password" ),
				$.$input( { class: "field-input", id: "resetpassFormPass", type: "password", name: "pass", required: true } ),
			),
			$.$label( { class: "field" },
				$.$span( { class: "field-label" }, "New password (confirmation)" ),
				$.$input( { class: "field-input", id: "resetpassFormPass2", type: "password", name: "pass2", required: true } ),
			),
			$.$div( { class: "form-error", id: "resetpassFormError" } ),
			$.$div( { class: "form-btns" },
				$.$elem( "gsui-com-button", { href: "#/auth", text: "Back to the login page" } ),
				$.$elem( "gsui-com-button", { type: "submit", text: "Save", id: "resetpassFormSubmit" } ),
			),
		),
	),
);
