"use strict";

$.$setTemplate( "gscoUser", () =>
	$.$div( { class: "page", id: "userPage" },
		$.$div( { id: "userPageTop" },
			$.$elem( "gsui-com-profile", { id: "userPageProfile" } ),
			$.$div( { id: "userPageProfileMenu" },
				$.$link( { class: "userPageProfileMenu-btn gsui-ellipsis", "data-action": "cmps" },
					$.$bold( { inert: true, id: "userPageProfileNbCmps" } ),
					$.$span( { inert: true, class: "gsui-ellipsis" }, "music·s" ),
				),
				$.$link( { class: "userPageProfileMenu-btn gsui-ellipsis", "data-action": "cmpsDeleted", "data-tooltip": "Composition <b>deleted</b>" },
					$.$bold( { inert: true, id: "userPageProfileNbCmpsDeleted" } ),
					$.$icon( { icon: "trash" } ),
				),
				$.$link( { class: "userPageProfileMenu-btn gsui-ellipsis", "data-action": "bio" },
					$.$bold( { inert: true, class: "gsui-ellipsis" }, "bio" ),
				),
				$.$link( { class: "userPageProfileMenu-btn gsui-ellipsis", "data-action": "cmpsLiked" },
					$.$bold( { inert: true, id: "userPageProfileNbCmpsLiked" } ),
					$.$span( { inert: true, class: "gsui-ellipsis" }, "like·s" ),
				),
			),
		),
		$.$div( { id: "userPageBio" } ),
		$.$div( { id: "userPagePlaylist" } ),
	),
);

$.$setTemplate( "gscoUserEditForm", p =>
	$.$flex( { id: "userPageEditForm", y: true, g12: true },
		$.$label( null,
			$.$span( null, "avatar" ),
			$.$div( null,
				$.$span( null, "GridSound accepts, for the moment, only " ),
				$.$linkExt( { href: "https://gravatar.com" },
					$.$icon( { icon: "br-wordpress" } ),
					$.$span( null, "WordPress - Gravatar" ),
				),
				$.$span( null, " as avatar." ),
			),
		),
		$.$label( null,
			$.$span( null, "first name" ),
			$.$input( { class: "userPageEditForm-input", type: "text", name: "firstname", value: p.firstname, spellcheck: "false" } ),
		),
		$.$label( null,
			$.$span( null, "last name" ),
			$.$input( { class: "userPageEditForm-input", type: "text", name: "lastname", value: p.lastname, spellcheck: "false" } ),
		),
		$.$label( null,
			$.$span( null, "email" ),
			$.$input( { class: "userPageEditForm-input", type: "email", name: "email", value: p.email, spellcheck: "false" } ),
			$.$span( null, "if the email is changed, a confirmation email has to be sent again" ),
		),
		$.$label( null,
			$.$span( null, "email public" ),
			$.$flex( { x: true },
				$.$input( { class: "userPageEditForm-input", type: "checkbox", name: "emailpublic", checked: p.emailpublic } ),
				$.$span( null, "if checked, your email will be public on your profile" ),
			),
		),
		$.$div( { id: "userPageEditFormError" } ),
	)
);
