"use strict";

GSUsetTemplate( "gs-userPage", () =>
	GSUcreateDiv( { class: "page", id: "userPage" },
		GSUcreateDiv( { id: "userPageTop" },
			GSUcreateElement( "gsui-com-profile", { id: "userPageProfile" } ),
			GSUcreateDiv( { id: "userPageProfileMenu" },
				GSUcreateDiv( { id: "userPageProfileMenuBg", inert: true } ),
				GSUcreateA( { class: "userPageProfileMenu-btn gsui-ellipsis", "data-action": "cmps" },
					GSUcreateSpan( { inert: true, id: "userPageProfileNbCmps" } ),
					GSUcreateSpan( { inert: true, class: "gsui-ellipsis" }, "composition·s" ),
				),
				GSUcreateA( { class: "userPageProfileMenu-btn gsui-ellipsis", "data-action": "cmpsDeleted" },
					GSUcreateSpan( { inert: true, id: "userPageProfileNbCmpsDeleted" } ),
					GSUcreateSpan( { inert: true, class: "gsui-ellipsis" }, "in the bin" ),
				),
				GSUcreateA( { class: "userPageProfileMenu-btn gsui-ellipsis", "data-action": "cmpsLiked" },
					GSUcreateSpan( { inert: true, id: "userPageProfileNbCmpsLiked" } ),
					GSUcreateSpan( { inert: true, class: "gsui-ellipsis" }, "like·s" ),
				),
			),
		),
		GSUcreateDiv( { id: "userPagePlaylist" } ),
	),
);

GSUsetTemplate( "gs-userPage-edit-form", p =>
	GSUcreateFlex( { id: "userPageEditForm", y: true, g12: true },
		GSUcreateLabel( null,
			GSUcreateSpan( null, "avatar" ),
			GSUcreateDiv( null,
				GSUcreateSpan( null, "GridSound accepts, for the moment, only " ),
				GSUcreateAExt( { href: "https://gravatar.com" },
					GSUcreateIcon( { icon: "br-wordpress" } ),
					GSUcreateSpan( null, "WordPress - Gravatar" ),
				),
				GSUcreateSpan( null, " as avatar." ),
			),
		),
		GSUcreateLabel( null,
			GSUcreateSpan( null, "first name" ),
			GSUcreateInput( { class: "userPageEditForm-input", type: "text", name: "firstname", value: p.firstname, spellcheck: "false" } ),
		),
		GSUcreateLabel( null,
			GSUcreateSpan( null, "last name" ),
			GSUcreateInput( { class: "userPageEditForm-input", type: "text", name: "lastname", value: p.lastname, spellcheck: "false" } ),
		),
		GSUcreateLabel( null,
			GSUcreateSpan( null, "email" ),
			GSUcreateInput( { class: "userPageEditForm-input", type: "email", name: "email", value: p.email, spellcheck: "false" } ),
			GSUcreateSpan( null, "if the email is changed, a confirmation email has to be sent again" ),
		),
		GSUcreateLabel( null,
			GSUcreateSpan( null, "email public" ),
			GSUcreateFlex( { x: true },
				GSUcreateInput( { class: "userPageEditForm-input", type: "checkbox", name: "emailpublic", checked: p.emailpublic } ),
				GSUcreateSpan( null, "if checked, your email will be public on your profile" ),
			),
		),
		GSUcreateDiv( { id: "userPageEditFormError" } ),
	)
);
