"use strict";

$.$setTemplate( "gs-main", () =>
	$.$div( { id: "root", class: "noauth" },
		$.$flex( { id: "bg", x: true, inert: false },
			$.$div( { "data-side": "start" },
				$.$div( { class: "bg-island", "data-name": "drums" } ),
				$.$div( { class: "bg-island", "data-name": "ipod" } ),
				$.$div( { class: "bg-island", "data-name": "piano" } ),
			),
			$.$div( { "data-side": "end" },
				$.$div( { class: "bg-island", "data-name": "tape" } ),
				$.$div( { class: "bg-island", "data-name": "ampli" } ),
				$.$div( { id: "bg-volcan" } ),
			),
		),
		$.$div( { id: "main" },
			$.$div( { id: "headWrap" },
				$.$div( { id: "head" },
					$.$link( { id: "headIcon", class: "headLink", href: "#/" } ),
					$.$link( { id: "headExplore", class: "headLink gsuiIcon", href: "#/explore", "data-icon": "users", "data-tooltip": GSTX.$exploreNewThings } ),
					$.$link( { id: "headSearch", class: "headLink gsuiIcon", href: "#/q", "data-icon": "search", "data-tooltip": GSTX.$searchUsersCmps } ),
					$.$div( { id: "headSep" } ),
					$.$linkExt( { id: "headNewCmp", class: "headLink gsuiIcon", href: gscoDAWURL, "data-icon": "cu-music-plus", "data-tooltip": GSTX.$createNewCmp } ),
					$.$link( { id: "headUser", class: "headLink gsui-ellipsis" },
						$.$div( { id: "headUsername", class: "gsui-ellipsis", inert: true } ),
						$.$elem( "gsui-com-avatar", { id: "headAvatar", inert: true } ),
					),
					$.$link( { id: "headAuth", class: "headLink gsuiIcon", href: "#/auth", "data-icon": "login", "data-spin": "on", "data-tooltip": GSTX.$user_login } ),
				),
			),
			$.$div( { id: "pages" },
				$.$div( { id: "loader" },
					$.$icon( { spin: true } ),
				),
				$.$div( { id: "error" },
					$.$span( { id: "errorLabel" }, "error" ),
					$.$span( { id: "errorCode" } ),
				),
			),
			$.$div( { id: "footer" },
				$.$div( { id: "footerSocialLinks" },
					$.$linkExt( { class: "gsuiIcon", "data-icon": "br-github", href: "//github.com/gridsound" } ),
					$.$linkExt( { class: "gsuiIcon", "data-icon": "br-codepen", href: "//codepen.io/gridsound" } ),
					$.$linkExt( { class: "gsuiIcon", "data-icon": "br-discord", href: "//discord.gg/NUYxHAg" } ),
					$.$linkExt( { class: "gsuiIcon", "data-icon": "br-bluesky", href: "//bsky.app/profile/gridsound.com" } ),
					$.$linkExt( { class: "gsuiIcon", "data-icon": "br-youtube", href: "//youtube.com/@gridsound" } ),
					$.$linkExt( { class: "gsuiIcon", "data-icon": "br-facebook", href: "//facebook.com/gridsound" } ),
				),
				$.$div( { id: "footerCopyright" }, GSTX.$copyright ),
			),
		),
	),
);
