"use strict";

$.$setTemplate( "gs-main", () =>
	$.$div( { id: "root", class: "noauth" },
		$.$flex( { id: "bg", x: true, inert: false },
			$.$div( { "data-side": "start" },
				$.$div( { class: "bg-island", "data-name": "drums" } ),
				$.$div( { class: "bg-island", "data-name": "ipod" } ),
				$.$div( { class: "bg-island", "data-name": "piano" } ),
			),
			$.$div( { "data-side": "end" },
				$.$div( { class: "bg-island", "data-name": "tape" } ),
				$.$div( { class: "bg-island", "data-name": "ampli" } ),
				$.$div( { id: "bg-volcan" } ),
			),
		),
		$.$div( { id: "main" },
			$.$div( { id: "headWrap" },
				$.$div( { id: "head" },
					$.$link( { id: "headIcon", class: "headLink", href: "#/" } ),
					$.$link( { id: "headExplore", class: "headLink", href: "#/explore", "data-tooltip": GSTX.$exploreNewThings }, $.$icon( { icon: "users" } ) ),
					$.$link( { id: "headSearch", class: "headLink", href: "#/q", "data-tooltip": GSTX.$searchUsersCmps }, $.$icon( { icon: "search" } ) ),
					$.$div( { id: "headSep" } ),
					$.$linkExt( { id: "headNewCmp", class: "headLink", href: GSURL.$gsDAW, "data-tooltip": GSTX.$createNewCmp }, $.$icon( { icon: "cu-music-plus" } ) ),
					$.$link( { id: "headUser", class: "headLink gsui-ellipsis" },
						$.$div( { id: "headUsername", class: "gsui-ellipsis", inert: true } ),
						$.$elem( "gsui-com-avatar", { id: "headAvatar", inert: true } ),
					),
					$.$link( { id: "headAuth", class: "headLink", href: "#/auth", "data-tooltip": GSTX.$user_login }, $.$icon( { icon: "login", spin: true } ) ),
				),
			),
			$.$div( { id: "pages" },
				$.$div( { id: "loader" },
					$.$icon( { spin: true } ),
				),
				$.$div( { id: "error" },
					$.$span( { id: "errorLabel" }, "error" ),
					$.$span( { id: "errorCode" } ),
				),
			),
			$.$div( { id: "footer" },
				$.$div( { id: "footerSocialLinks" },
					$.$linkExt( { href: GSURL.$github   }, $.$icon( { icon: "br-github"   } ) ),
					$.$linkExt( { href: GSURL.$codepen  }, $.$icon( { icon: "br-codepen"  } ) ),
					$.$linkExt( { href: GSURL.$discord  }, $.$icon( { icon: "br-discord"  } ) ),
					$.$linkExt( { href: GSURL.$bluesky  }, $.$icon( { icon: "br-bluesky"  } ) ),
					$.$linkExt( { href: GSURL.$youtube  }, $.$icon( { icon: "br-youtube"  } ) ),
					$.$linkExt( { href: GSURL.$facebook }, $.$icon( { icon: "br-facebook" } ) ),
				),
				$.$div( { id: "footerCopyright" }, GSTX.$copyright ),
			),
		),
	),
);
