"use strict";

$.$setTemplate( "gscoSearch", () =>
	$.$div( { class: "page", id: "searchPage" },
		$.$div( { id: "searchPage-intro" }, GSTX.$searchOnGS ),
		$.$elem( "form", { id: "searchPageForm" },
			$.$div( { id: "searchPageFormFilter" },
				$.$label( null,
					$.$input( { name: "search-filter", type: "radio", value: "u" } ),
					$.$span( null, GSTX.$user ),
				),
				$.$label( null,
					$.$input( { name: "search-filter", type: "radio", value: "cmp" } ),
					$.$span( null, GSTX.$composition ),
				),
			),
			$.$div( { id: "searchPageFormBody" },
				$.$input( { id: "searchPageFormQ", type: "text", placeholder: GSTX.$searchDots, autocomplete: "off" } ),
				$.$button( { id: "searchPageFormSubmit", type: "submit", class: "gsuiIcon", icon: "search" } ),
			),
		),
		$.$div( { id: "searchPageResultIntro" } ),
		$.$div( { id: "searchPageResult" } ),
	),
);
