"use strict";

GSUsetTemplate( "gs-cmp", () =>
	GSUcreateDiv( { class: "cmp" },
		GSUcreateDiv( { class: "cmpPlay gsuiIcon", "data-icon": "play" } ),
		GSUcreateDiv( { class: "cmpBody" },
			GSUcreateDiv( { class: "cmpText" },
				GSUcreateDiv( { class: "cmpName" },
					GSUcreateA( { class: "cmpNameLink" } ),
				),
				GSUcreateDiv( { class: "cmpInfo" },
					GSUcreateDiv( { class: "cmpTime" },
						GSUcreateI( { class: "gsuiIcon", "data-icon": "clock" } ),
						GSUcreateDiv( { class: "cmpCurrentTime" } ),
						GSUcreateDiv( { class: "cmpDur" } ),
					),
					GSUcreateDiv( { class: "cmpBPMwrap" },
						GSUcreateI( { class: "gsuiIcon", "data-icon": "speed" } ),
						GSUcreateSpan( { class: "cmpBPM" } ),
					),
				),
			),
			GSUcreateDiv( { class: "cmpSlider" },
				GSUcreateDiv( { class: "cmpSliderValue" } ),
				GSUcreateDiv( { class: "cmpSliderInput", type: "range", min: 0, step: .001, value: 0 } ),
			),
		),
		GSUcreateA( { class: "cmpUser" },
			GSUcreateI( { class: "gsuiIcon", "data-icon": "musician" } ),
			GSUcreateDiv( { class: "cmpUserAvatar" } ),
			GSUcreateSpan( { class: "cmpUserUsername" } ),
			GSUcreateSpan( { class: "cmpUserName" } ),
		),
	),
);
