"use strict";

GSUsetTemplate( "gs-main", () =>
	GSUcreateDiv( { id: "main", class: "noauth" },
		GSUcreateDiv( { id: "head" },
			GSUcreateA( { id: "headIcon", class: "headLink", href: "#/" } ),
			GSUcreateA( { id: "headUser", class: "headLink" },
				GSUcreateDiv( { id: "headUsername" } ),
				GSUcreateDiv( { id: "headAvatar", class: "userAvatar" },
					GSUcreateElement( "img", { id: "headAvatarImg", class: "userAvatarImg" } ),
					GSUcreateI( { class: "userAvatarDef gsuiIcon", "data-icon": "musician" } ),
				),
			),
			GSUcreateA( { id: "headAuth", class: "headLink gsuiIcon", href: "#/auth", "data-icon": "login", "data-spin": "on", title: "Authentication" } ),
		),
		GSUcreateDiv( { id: "pages" },
			GSUcreateDiv( { id: "loader" },
				GSUcreateI( { class: "gsuiIcon", "data-spin": "on" } ),
			),
			GSUcreateDiv( { id: "error" },
				GSUcreateSpan( { id: "errorLabel" }, "error" ),
				GSUcreateSpan( { id: "errorCode" } ),
			),
		),
		GSUcreateDiv( { id: "footer" },
			GSUcreateDiv( { id: "footerContent" },
				GSUcreateDiv( { class: "footer-line" },
					GSUcreateSpan( { class: "footer-label" }, "GridSound's applications" ),
					GSUcreateAExt( { href: "https://gridsound.com/daw/" },
						GSUcreateI( { class: "gsuiIcon", "data-icon": "music" } ),
						GSUcreateElement( "b", null, " DAW" ),
					),
				),
				GSUcreateDiv( { class: "footer-line" },
					GSUcreateSpan( { class: "footer-label" }, "GridSound on the web" ),
					GSUcreateDiv( { id: "footerSocialsLink" },
						GSUcreateAExt( { class: "gsuiIcon gsuiIconB", "data-icon": "github", href: "https://github.com/gridsound" } ),
						GSUcreateAExt( { class: "gsuiIcon gsuiIconB", "data-icon": "codepen", href: "https://codepen.io/gridsound" } ),
						GSUcreateAExt( { class: "gsuiIcon gsuiIconB", "data-icon": "discord", href: "https://discord.gg/NUYxHAg" } ),
						GSUcreateAExt( { class: "gsuiIcon gsuiIconB", "data-icon": "twitter", href: "https://twitter.com/gridsound" } ),
						GSUcreateAExt( { class: "gsuiIcon gsuiIconB", "data-icon": "youtube", href: "https://youtube.com/@gridsound" } ),
						GSUcreateAExt( { class: "gsuiIcon gsuiIconB", "data-icon": "facebook", href: "https://facebook.com/gridsound" } ),
					),
				),
				GSUcreateDiv( { class: "footer-line", id: "footerCopyright" }, "© 2024 gridsound.com all rights reserved" ),
			),
		),
	),
);
