"use strict";

GSUsetTemplate( "gs-userPage", () =>
	GSUcreateDiv( { class: "page", id: "userPage" },
		GSUcreateElement( "gsui-com-profile", { id: "gsuiComProfile" } ),
		GSUcreateDiv( { class: "pageSection" },
			GSUcreateDiv( { class: "pageSectionTitle" },
				GSUcreateA( { class: "userPageMenuLink", href: false, id: "userPageNbCompositions" },
					GSUcreateSpan( { class: "pageSectionTitleValue" } ),
					GSUcreateSpan( { class: "pageSectionTitleLabel" }, "composition·s" ),
				),
				GSUcreateA( { class: "userPageMenuLink", href: false, id: "userPageNbCompositionsDeleted" },
					GSUcreateSpan( { class: "pageSectionTitleValue" }, 0 ),
					GSUcreateSpan( { class: "pageSectionTitleLabel" }, "in the bin" ),
				),
			),
			GSUcreateDiv( { class: "pageSectionBody", id: "userPageCmps" } ),
			GSUcreateDiv( { class: "pageSectionPlaceHolder", id: "userPageCmpsPlaceholder" },
				GSUcreateSpan( { class: "pageSectionPlaceHolder-text" },
					GSUcreateSpan( null, "No saved composition yet" ),
					GSUcreateSpan( null, ", you should create a new one right now!" ),
				),
				GSUcreateDiv( { class: "pageSectionPlaceHolder-draw" },
					GSUcreateI( { class: "gsuiIcon", "data-icon": "music" } ),
				),
			),
			GSUcreateDiv( { class: "pageSectionPlaceHolder", id: "userPageCmpsDeletedPlaceholder" },
				GSUcreateSpan( { class: "pageSectionPlaceHolder-text" }, "There is no composition inside your bin." ),
				GSUcreateDiv( { class: "pageSectionPlaceHolder-draw" },
					GSUcreateI( { class: "gsuiIcon", "data-icon": "trash" } ),
				),
			),
		),
	),
);
